name: build-k0fiscan

on:
  push:
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_cross: true

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use_cross: true

          - os: macos-latest
            target: x86_64-apple-darwin
            use_cross: false

          - os: macos-latest
            target: aarch64-apple-darwin
            use_cross: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross (Linux targets only)
        if: matrix.use_cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build binary
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Package tar.gz
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf k0fiscan-${{ matrix.target }}.tar.gz k0fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: k0fiscan-${{ matrix.target }}.tar.gz
          path: target/${{ matrix.target }}/release/k0fiscan-${{ matrix.target }}.tar.gz

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/k0fiscan-${{ matrix.target }}.tar.gz
